# Generated by Django 2.2.24 on 2023-10-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_entities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Photo Pokemon"
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title",
            field=models.CharField(blank=True, max_length=200, verbose_name="Pokemon"),
        ),
    ]
