# Generated by Django 2.2.24 on 2023-10-31 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_entities", "0003_pokemonentity"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemonentity",
            name="pokemon",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="pokemon_entities.Pokemon",
                verbose_name="Модель Покемона",
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Фото Покемона"
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Название Покемон"
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="latitude",
            field=models.FloatField(verbose_name="Широта"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="longitude",
            field=models.FloatField(verbose_name="Долгота"),
        ),
    ]
