# Generated by Django 2.2.24 on 2023-10-31 15:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_entities", "0004_auto_20231031_1826"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 31, 18, 46, 3, 555001),
                verbose_name="Появляется",
            ),
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 31, 23, 46, 3, 555001),
                verbose_name="Исчезает",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="pokemon",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pokemon_entities.Pokemon",
                verbose_name="Покемон",
            ),
        ),
    ]
