# Generated by Django 2.2.24 on 2023-10-31 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_entities", "0005_auto_20231031_1846"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemonentity",
            name="defence",
            field=models.IntegerField(default=None, verbose_name="Защита"),
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="health",
            field=models.IntegerField(default=None, verbose_name="Здоровье"),
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="level",
            field=models.IntegerField(default=None, verbose_name="Уровень"),
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="stamina",
            field=models.IntegerField(default=None, verbose_name="Выносливость"),
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="strength",
            field=models.IntegerField(default=None, verbose_name="Сила"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 31, 19, 4, 31, 588761),
                verbose_name="Появляется",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 1, 0, 4, 31, 588761),
                verbose_name="Исчезает",
            ),
        ),
    ]
