# Generated by Django 2.2.24 on 2023-11-14 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_entities", "0006_auto_20231031_1904"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pokemon",
            name="title",
        ),
        migrations.AddField(
            model_name="pokemon",
            name="description",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Описание Покемона"
            ),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Название Покемон Англ."
            ),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="title_jp",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Название Покемон Англ."
            ),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="title_ru",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Название Покемон Рус."
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 14, 18, 33, 57, 414686),
                verbose_name="Появляется",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 14, 23, 33, 57, 414686),
                verbose_name="Исчезает",
            ),
        ),
    ]
