# Generated by Django 2.2.24 on 2023-11-14 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_entities", "0007_auto_20231114_1833"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 14, 18, 35, 14, 273615),
                verbose_name="Появляется",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 14, 23, 35, 14, 273615),
                verbose_name="Исчезает",
            ),
        ),
    ]
