# Generated by Django 2.2.24 on 2023-11-14 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_entities", "0008_auto_20231114_1835"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pokemon",
            old_name="title_ru",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title_jp",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Название Покемон Япн."
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 14, 18, 40, 21, 972577),
                verbose_name="Появляется",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 14, 23, 40, 21, 972577),
                verbose_name="Исчезает",
            ),
        ),
    ]
