# Generated by Django 2.2.24 on 2023-11-14 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_entities", "0009_auto_20231114_1840"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="description",
            field=models.TextField(
                blank=True, max_length=200, verbose_name="Описание Покемона"
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 14, 18, 43, 45, 25019),
                verbose_name="Появляется",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 14, 23, 43, 45, 25019),
                verbose_name="Исчезает",
            ),
        ),
    ]
