# Generated by Django 2.2.24 on 2023-11-14 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_entities", "0010_auto_20231114_1843"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание Покемона"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 14, 18, 47, 50, 85339),
                verbose_name="Появляется",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 14, 23, 47, 50, 85339),
                verbose_name="Исчезает",
            ),
        ),
    ]
