# Generated by Django 2.2.24 on 2023-11-16 15:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_entities", "0013_auto_20231116_1836"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="previous_evolution",
                to="pokemon_entities.Pokemon",
                verbose_name="Из кого эволюционирует",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 16, 18, 48, 48, 180455),
                verbose_name="Появляется",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 16, 23, 48, 48, 181385),
                verbose_name="Исчезает",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="pokemon",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entity",
                to="pokemon_entities.Pokemon",
                verbose_name="Покемон",
            ),
        ),
    ]
