# Generated by Django 2.2.24 on 2023-11-17 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_entities", "0027_auto_20231117_2117"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 17, 21, 19, 39, 713588),
                verbose_name="Появляется",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 18, 2, 19, 39, 713588),
                verbose_name="Исчезает",
            ),
        ),
    ]
