# Generated by Django 2.2.24 on 2023-11-28 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_entities", "0033_auto_20231126_1750"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 28, 18, 7, 17, 252704),
                verbose_name="Появляется",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 28, 23, 7, 17, 252704),
                verbose_name="Исчезает",
            ),
        ),
    ]
