# Generated by Django 2.2.24 on 2023-11-28 15:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_entities", "0034_auto_20231128_1807"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 28, 18, 16, 47, 836024),
                verbose_name="Появляется",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 28, 23, 16, 47, 836024),
                verbose_name="Исчезает",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="pokemon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pokemons",
                to="pokemon_entities.Pokemon",
                verbose_name="Покемон",
            ),
        ),
    ]
